version: "3"
# Names our volume
volumes:
  todoApp-db:

services:
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Password
      - MYSQL_DATABASE=todoapp

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"

    volumes:
      - todoApp-db:/var/lib/mysql

  todo-app1:
    environment:
      - NODE_ENV=production
    build: ../todoApp-MySQL
    container_name: todo-app1
    ports:
      - 5001:5000
    links:
      - mysql
    depends_on:
      - mysql

  todo-app2:
    environment:
      - NODE_ENV=production
      - MYNAME=Paula
    build: ../todoApp-MySQL
    container_name: todo-app2
    ports:
      - 5002:5000
    links:
      - mysql
    depends_on:
      - mysql
  load-balancer:
    restart: always
    container_name: loadbalancer
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 8080:80
    depends_on:
      - todo-app1
      - todo-app2
